### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by obluda3** [hotandcoldcoffee/Wayback-Machine-Searcher#1]
Would it be possible to disclose the source of this program? It will help fixing potential bugs and adding more features to it as well as making it a bit more trustworthy.

Thanks.

**Comment by hotandcoldcoffee** [comment]
> Would it be possible to disclose the source of this program? It will help fixing potential bugs and adding more features to it as well as making it a bit more trustworthy.
> 
> Thanks.

waybacksearch.py is the source code

**Comment by obluda3** [comment]
Thanks
